### ISSUE TITLE
Spark dependencies are provided by design, not a bug.

### ISSUE THREAD

**Issue by amitsela** [eljefe6a/beamexample#3]
In https://github.com/eljefe6a/beamexample/blob/master/BeamTutorial/pom.xml#L93 it says that the dependencies need to be explicitly added because of a bug. That is wrong. They need to be explicitly added because they are scope `provided` in the runner pom.

Spark is **usually** deployed in production clusters and applications depend on it with scope `provided` or `runtime`.
One good reason is the fact that the Spark distribution used needs to match the backend: `YARN`, `Mesos`, `Stand Alone`.
Another reason is the fact that if using Spark with Hadoop, you have to use a Hadoop-specific build - see [here](http://spark.apache.org/downloads.html).

**Comment by eljefe6a** [comment]
I think the bug I'm referring to is that the Spark runner is initializing even though it isn't being used.

**Comment by amitsela** [comment]
I think that has to do with multiple `PipelineOptions` implementations in the classpath. It seems that `PipelineOptionsFactory` scans through all implementations in the classpath and tries to load them.
the dependency on the Spark runner brings along the `SparkPipelineOptions` into the classpath, but it has a `provided` dependency on Spark, which is non-transitive.
That's just Maven-math....

**Comment by amitsela** [comment]
Confirmed - I debugged this, that's exactly what happens.
Anyway - not a bug - maybe something along the lines of:
"Spark is usually pre-deployed on the cluster and so the Spark runner _currently_ scopes it as provided, so we will add it explicitly".
BTW, this is done the same in the Beam examples E2E IT tests [here](https://github.com/apache/incubator-beam/blob/master/examples/java/pom.xml#L95).

**Comment by eljefe6a** [comment]
We have to call it something so people will know how to workaround it. How about calling it a limitation and I'll link this issue URL?

**Comment by amitsela** [comment]
But this is not a limitation, if the runner was pre-built with a specific Spark-hadoop release. How would you use it on pre-deployed clusters ?
Example: runner built with common latest (stable) Spark release 1.6.2 (Hadoop 2.2.0). Now the runner might not be used on any YARN deployment that is not Hadoop 2.2.0.

**Comment by amitsela** [comment]
Spark have separate builds just for that... out choice is to have custom builds for their custom builds, that's a bad road to go down...

**Comment by amitsela** [comment]
One way to go:
`
    `

**Comment by eljefe6a** [comment]
Will remove the text from the comment and say `See this for more information`

**Comment by amitsela** [comment]
👍

**Comment by eljefe6a** [comment]
Fair enough. I'll use your comment and point them here.

**Comment by amitsela** [comment]
👍 👍 👍
